Feat: Add support for generating and sending weekly newsletter emails.
Tietokilta/web pull request #468
Opened 2024-09-01 16:35 UTC by Mikmokki

## Description

- ...

### Before submitting the PR, please make sure you do the following

- [X] If your PR is related to a previously discussed issue, please [link to it](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) here.
- 
https://github.com/Tietokilta/web/issues/243

- [X] Prefix your PR title with feat:, fix:, chore:, or docs:.
- [X] This message body should clearly illustrate what problems it solves.
- [X] Make sure the commit history is linear, up-to-date with main branch and does not contain any erroneous changes

### Formatting and linting

- [X] Format code with `pnpm format` and lint the project with `pnpm lint`

2024-09-01 17:51 UTC, Mikmokki commented on apps/cms/src/controllers/newsletter-controller.ts
> +    })) as unknown as WeeklyNewsletter;
Tää on kyl kauhee. Buildi jäi tästä kii

2024-09-09 18:02 UTC, joonatanaatos requested changes

2024-09-09 18:02 UTC, joonatanaatos commented on apps/cms/src/controllers/newsletter-controller.ts
> +  const { newsletterId } = req.params;
Check for authorization

2024-09-09 21:18 UTC, Mikmokki commented on apps/cms/src/emails/helper-components.tsx
> +            return <blockquote key={index}>{serializedChildren}</blockquote>;
Toimi kun testasin mailil.

2024-09-10 06:39 UTC, joonatanaatos approved these changes

2024-09-10 08:01 UTC, merged