fix: encode filenames before posting to laskugeneraattori
Tietokilta/web pull request #523
Opened 2024-10-14 11:55 UTC by MikaelSiidorow

## Description

- fix: encode filenames before posting to laskugeneraattori

Closes #522 

### Before submitting the PR, please make sure you do the following

- [x] If your PR is related to a previously discussed issue, please [link to it](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) here.
- [x] Prefix your PR title with feat:, fix:, chore:, or docs:.
- [x] This message body should clearly illustrate what problems it solves.
- [x] Make sure the commit history is linear, up-to-date with main branch and does not contain any erroneous changes

### Formatting and linting

- [x] Format code with `pnpm format` and lint the project with `pnpm lint`

2024-10-14 12:14 UTC, IiroP requested changes
Does not work (at least without changes to backend)

![image](https://github.com/user-attachments/assets/823d1287-5539-43c1-80fd-cbd8f8f451b6)

2024-10-15 08:13 UTC, lajp commented
I'm not sure how it is done right now but apparently non-ascii characters are to be included, they should be added to the `filename*` field with the [RFC 5987 encoding](https://datatracker.ietf.org/doc/html/rfc5987)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#syntax
> You may want to avoid percent escape sequences in filename, because they are handled inconsistently across browsers.

2024-10-16 08:54 UTC, MikaelSiidorow commented
> I'm not sure how it is done right now but apparently non-ascii characters are to be included, they should be added to the `filename*` field with the [RFC 5987 encoding](https://datatracker.ietf.org/doc/html/rfc5987)
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#syntax
> 
> > You may want to avoid percent escape sequences in filename, because they are handled inconsistently across browsers.

@lajp I'll take a look. We are using a higher level abstraction with [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) and [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), that _should_ do the right thing automatically...

2024-10-16 19:45 UTC, lajp commented
I found a potential cause for this. Apparently `multer`, the crate used by `axum::extract::Multipart` doesn't support the `filename*`-field: https://github.com/rwf2/multer/issues/52

2024-10-23 12:20 UTC, MikaelSiidorow commented
We could also just slugify the original filenames and strip special characters as a workaround, I doubt that would affect any invoices negatively :thinking: Could do it in similarly like we do with heading IDs for rich text

2025-02-04 14:46 UTC, closed without merging